services:
  joker-login-queue-server:
    build: .
    environment:
      REDIS_HOST: ${REDIS_HOST:?err}
      REDIS_DB: ${REDIS_DB:?err}
      SERVER_PORT: ${SERVER_PORT:?err}
      MAIN_SERVER_HOST: ${MAIN_SERVER_HOST:?err}
      MAIN_SERVER_API_KEY: ${MAIN_SERVER_API_KEY:?err}
      TLS_PRIVATE_KEY_PATH: ${TLS_PRIVATE_KEY_PATH:?err}
      TLS_CERT_PATH: ${TLS_CERT_PATH:?err}
    command:
      - --session-stale-seconds=${SESSION_STALE_SECONDS:?err}
      - --ticket-stale-seconds=${TICKET_STALE_SECONDS:?err}
      - --notify-stats-interval-seconds=${NOTIFY_STATS_INTERVAL_SECONDS:?err}
      - --dequeue-interval-seconds=${DEQUEUE_INTERVAL_SECONDS:?err}
      - --max-dequeue-per-interval=${MAX_DEQUEUE_PER_INTERVAL:?err}
      - --init-avg-wait-seconds=${INIT_AVG_WAIT_SECONDS:?err}
      - --average-wait-window-size=${AVERAGE_WAIT_WINDOW_SIZE:?err}
      - --ping-interval-seconds=${PING_INTERVAL_SECONDS:?err}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '5'
        compress: 'true'
    ports:
      - ${SERVER_PORT:?err}:${SERVER_PORT:?err}
    networks:
      - backend
    volumes:
      - type: bind
        source: ./deploy
        target: /deploy
networks:
  backend:
    driver: bridge
