// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func Setup() *Server {
	config := ProvideConfig()
	stats := ProvideStats()
	queue := ProvideQueue(stats, config)
	hub := ProvideHub(queue)
	application := ProvideApplication(config, hub, queue)
	server := ProvideServer(application)
	return server
}
