// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"game-soul-technology/joker/joker-login-queue-server/pkg/client"
	"game-soul-technology/joker/joker-login-queue-server/pkg/config"
	"game-soul-technology/joker/joker-login-queue-server/pkg/infra"
	"game-soul-technology/joker/joker-login-queue-server/pkg/queue"
)

// Injectors from wire.go:

func Setup() (*Server, error) {
	loggerFactory := infra.ProvideLoggerFactory()
	redisClient, err := infra.ProvideRedisClient(loggerFactory)
	if err != nil {
		return nil, err
	}
	configConfig := config.ProvideConfig(redisClient, loggerFactory)
	stats := queue.ProvideStats(loggerFactory)
	queueQueue := queue.ProvideQueue(stats, configConfig, loggerFactory)
	reqClient := infra.ProvideHttpClient()
	hub := client.ProvideHub(queueQueue, reqClient, loggerFactory)
	clientFactory := client.ProvideClientFactory(hub, loggerFactory)
	application := ProvideApplication(configConfig, clientFactory, hub, queueQueue, loggerFactory)
	server := ProvideServer(application, reqClient, loggerFactory)
	return server, nil
}
