// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"game-soul-technology/joker/joker-login-queue-server/pkg/client"
	"game-soul-technology/joker/joker-login-queue-server/pkg/config"
	"game-soul-technology/joker/joker-login-queue-server/pkg/queue"
)

// Injectors from wire.go:

func Setup() *Server {
	configConfig := config.ProvideConfig()
	clientFactory := client.ProvideClientFactory()
	stats := queue.ProvideStats()
	queueQueue := queue.ProvideQueue(stats, configConfig)
	hub := client.ProvideHub(queueQueue)
	application := ProvideApplication(configConfig, clientFactory, hub, queueQueue)
	server := ProvideServer(application)
	return server
}
